### ISSUE TITLE
Update Django Version

### ISSUE THREAD

**Issue by cvanoort** [compstorylab/sirius#1]
This project is using an unsecure version of Django. `requirements.txt` has [Django = 2.0.12](https://github.com/compstorylab/sirius/blob/eb110e9693581b4eaddc68e160f451935d8b04af/requirements.txt#L1). Github recommends upgrading to [Django >= 2.2.9](https://github.com/compstorylab/sirius/network/alert/requirements.txt/Django/open) and the most recent version appears to be [Django = 3.0.2](https://www.djangoproject.com/download/).

**Comment by xyz8983** [comment]
Thank you for the review! I have updated the version of Django to 3.0.2
